{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
{{- if and ( .Values.exporter.enabled ) ( .Values.exporter.serviceMonitor.enabled ) }}
    servicemonitor: enabled
{{- end }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: NodePort
  clusterIP: None
  ports:
  - name: exporter-port
    port: {{ .Values.exporter.port }}
    protocol: TCP
    targetPort: exporter-port
  selector:
    release: {{ .Release.Name }}
    app: {{ template "redis-ha.name" . }}
{{- end }}